### ISSUE TITLE
keep it simple

### ISSUE THREAD

**Issue by sunaku** [mplewis/shed#1]
Python seems overkill for what this does. :scream: A shell script would suffice:

https://gist.github.com/sunaku/f5f79e20b6f92ab1e524

Cheers. :santa:

**Comment by kinduff** [comment]
:+1:

**Comment by christianbundy** [comment]
Or [`vipe`](http://linux.die.net/man/1/vipe)

``` shell
curl -L https://npmjs.org/install.sh | vipe | sh
```

**Comment by sunaku** [comment]
:+1: for vipe! :runner: Had to `apt-get install moreutils` under Ubuntu 15.04 for it.

**Comment by mplewis** [comment]
Thanks for the suggestions! Never knew about vipe before @christianbundy.

I learned a lot from @sunaku's script—how to grep for yes/no and other stuff. Thanks so much for writing that!

**Comment by mplewis** [comment]
Added a note to the readme. Thanks again.
